### ISSUE TITLE
Problemy z modelem

### ISSUE THREAD

**Issue by Alerione** [JakubGolebiowski/si4music-images-to-music-GAN-generator#3]
Nie wiem do końca czego to jest kwestia, i czy da się to sensownie naprawić, ale przeglądając macierze, jakie generuje w tym momencie model 50k (i 100k chyba, ale mniej wygenerowałem tam, żeby obejrzeć) jest duży odchył wartości velocity na ujemne.
Poza pojedynczymi przypadkami albo daje ujemne z całego zakresu (-128~0, dużo w granicach -128~-80) albo dodatnie z niskiego zakresu (0~30).

Jest to niestety duży issue, bo często się generuje midi z samymi ujemnymi (czyli de facto pusty) lub z tylko niskimi wartościami velocity (nuty zagrane na niskich velocity ledwo słychać). O samą jakość muzyki to tam kij, ale jak nie ma dźwięku to słabo będzie.

**Comment by JakubGolebiowski** [comment]
Zmienię sposób normalizacji w postprocessingu względem min-max wartości z wyjścia z modelu

**Comment by JakubGolebiowski** [comment]
Dodałem osobne normalizacje dla danych z 3ch zakresów, niestety masa ciężkości z modelu 50K wypada na liczby ujemne więc nadal mamy w większości liczby ujemne, ale 3-5x więcej liczb dodatnich o wyższych wartościach, na razie powinno być ok.
